server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ =404;
    }

    # 캐시 설정
    location ~* \.(jpg|jpeg|png|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
    location ~* \.(html)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}
